#!/bin/bash
#plugin Paragraph is mandatory in src/components/tools/ ...
DIR="src/components/tools/paragraph"
if ! [ "$(ls -A $DIR)" ]; then
#...yarn will do a git clone equivalent to install it 
yarn install
yarn pull_tools
fi
npm run-script build:dev
