import UI from '../src/components/modules/ui';
import BlockEvents from '../src/components/modules/blockEvents';
import Listeners from '../src/components/modules/listeners';
import Toolbar from '../src/components/modules/toolbar';
import InlineToolbar from '../src/components/modules/toolbar/inline';
import Toolbox from '../src/components/modules/toolbar/toolbox';
import BlockSettings from '../src/components/modules/toolbar/blockSettings';
import Events from '../src/components/modules/events';
import Shortcuts from '../src/components/modules/shortcuts';
import Paste from '../src/components/modules/paste';
import DragNDrop from '../src/components/modules/dragNDrop';
import ModificationsObserver from '../src/components/modules/modificationsObserver';
import Renderer from '../src/components/modules/renderer';
import Sanitizer from '../src/components/modules/sanitizer';
import Tools from '../src/components/modules/tools';
import API from '../src/components/modules/api';
import Caret from '../src/components/modules/caret';
import BlockManager from '../src/components/modules/blockManager';
import BlocksAPI from '../src/components/modules/api/blocks';
import CaretAPI from '../src/components/modules/api/caret';
import EventsAPI from '../src/components/modules/api/events';
import ListenersAPI from '../src/components/modules/api/listeners';
import SanitizerAPI from '../src/components/modules/api/sanitizer';
import ToolbarAPI from '../src/components/modules/api/toolbar';
import StylesAPI from '../src/components/modules/api/styles';
import SelectionAPI from '../src/components/modules/api/selection';
import SaverAPI from '../src/components/modules/api/saver';
import Saver from '../src/components/modules/saver';

export interface EditorModules {
  UI: UI;
  BlockEvents: BlockEvents;
  Listeners: Listeners;
  Toolbar: Toolbar;
  InlineToolbar: InlineToolbar;
  Toolbox: Toolbox;
  BlockSettings: BlockSettings;
  Events: Events;
  Shortcuts: Shortcuts;
  Paste: Paste;
  DragNDrop: DragNDrop;
  ModificationsObserver: ModificationsObserver;
  Renderer: Renderer;
  Sanitizer: Sanitizer;
  Tools: Tools;
  API: API;
  Caret: Caret;
  Saver: Saver;
  BlockManager: BlockManager;
  BlocksAPI: BlocksAPI;
  CaretAPI: CaretAPI;
  EventsAPI: EventsAPI;
  ListenerAPI: ListenersAPI;
  SanitizerAPI: SanitizerAPI;
  SaverAPI: SaverAPI;
  SelectionAPI: SelectionAPI;
  StylesAPI: StylesAPI;
  ToolbarAPI: ToolbarAPI;
}
